### ISSUE TITLE
npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated

### ISSUE THREAD

**Issue by jimbrayrcp** [dkruythoff/gulp-inline-image#2]
npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at [https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5](https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5)

**Comment by medonagy45** [comment]
please close
